name: Laravel

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest


    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.0"
    - name: Create Database
      run: mysql -uroot -e 'CREATE DATABASE [IF NOT EXISTS] laravel'
    - name: Test Database
      run: |
        mysql -uroot -e 'SHOW DATABASES; use laravel; SHOW TABLES;'
    - uses: actions/checkout@v3
    - name: Copy .env
      working-directory: ./LaravelOmgeving
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ./LaravelOmgeving
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Generate key
      working-directory: ./LaravelOmgeving
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./LaravelOmgeving
      run: chmod -R 777 storage bootstrap/cache
    - name: Use NPM
      working-directory: ./LaravelOmgeving
      run: |
        npm install
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      working-directory: ./LaravelOmgeving
      run: | 
        php artisan migrate:fresh --seed
        php artisan test
