name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      working-directory: ./LaravelOmgeving
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    -name: Setup application for SQLite
      run: |
        touch database/database.sqlite
        echo "DB_CONNECTION=sqlite" >> LaravelOmgeving/.env
        echo "DB_DATABASE=$/.github/workflows/laravel/database/database.sqlite" >> LaravelOmgeving/.env
    - name: Install Dependencies
      working-directory: ./LaravelOmgeving
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Generate key
      working-directory: ./LaravelOmgeving
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./LaravelOmgeving
      run: chmod -R 777 storage bootstrap/cache
    - name: Use NPM
      working-directory: ./LaravelOmgeving
      run: |
        npm install
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      working-directory: ./LaravelOmgeving
      run: | 
        php artisan migrate:fresh --seed
        php artisan test
