name: Laravel-tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      working-directory: LaravelOmgeving
      run: | 
        php artisan migrate:fresh --seed
        php artisan test